name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@master
       
#        - name: set up java jdk
#          uses: actions/setup-java@v1
#          with: 
#             java-version: 1.8
#        - name: github context
#          env:
#            GITHUB_CONTEXT: ${{toJSON(github)}}
#          run: echo "${{ github.event.commits[0].id}}"
       - name: Publish to Registry
         uses: elgohr/Publish-Docker-Github-Action@master
         with:
            name: ziminga/ziming-test1:${{github.event.commits[0].id}}
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      #  - name: executing remote ssh commands using password
      #    uses: appleboy/ssh-action@master
      #    with:
      #       host: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
      #       username: root
      #       password: ${{ secrets.TENCENT_CLOUD_SECRET_KEY}}
      #       port: 22
      #       script: |
      #         docker pull ziminga/ziming-blog
      #         kubectl set image deployments/demo-frontend frontend-app=ziminga/ziming-blog:${{github.event.commits[0].id}}

